Add sweep token to token lock
hats-finance/hats-contracts pull request #111
Opened 2022-03-23 16:59 UTC by ben-kaufman

Fix #108

2022-03-29 13:01 UTC, jellegerbrandy requested changes

2022-03-29 20:39 UTC, ben-kaufman commented on contracts/tokenlock/TokenLock.sol
> +        require(_token != token, "cannot sweep vested token");
But if the token contract is malicious then we can't really trust the balanceOf either no?

2022-04-04 11:02 UTC, jellegerbrandy commented on contracts/tokenlock/TokenLock.sol
> +        require(_token != token, "cannot sweep vested token");
Well, in this case the token was not malicious. I guess they had like an old contract and then an upgrade or something, and wanted to keep both addresses to interact with the same balances.

2022-04-04 11:04 UTC, jellegerbrandy approved these changes

2022-04-04 11:04 UTC, merged