add _descriptionHash to SubmitClaim
hats-finance/hats-contracts pull request #182
Opened 2022-05-26 16:38 UTC by lirona

2022-05-27 09:28 UTC, jellegerbrandy requested changes
this is all good. We should also have a test for this event though. The only place in the tests where this event is tested is on line 1751 - we should test there also if actually the descirption hash is part of the event (just add a line below)

2022-05-29 10:22 UTC, lirona commented
> this is all good. We should also have a test for this event though. The only place in the tests where this event is tested is on line 1751 - we should test there also if actually the descirption hash is part of the event (just add a line below)

link to line please? :)

2022-05-29 10:23 UTC, lirona commented
> this is all good. We should also have a test for this event though. The only place in the tests where this event is tested is on line 1751 - we should test there also if actually the descirption hash is part of the event (just add a line below)

not the right line..

2022-05-29 13:38 UTC, jellegerbrandy approved these changes

2022-05-29 13:38 UTC, merged