Fix #233
hats-finance/hats-contracts pull request #245
Opened 2022-06-20 20:32 UTC by ben-kaufman

Fix #233

2022-06-21 09:20 UTC, jellegerbrandy approved these changes

2022-06-21 09:28 UTC, jellegerbrandy requested changes
These fixes are good, but lets also change the error message in dismissClaim from `OnlyCallableByGovernanceOrAfterChallengeTimeOutPeriod` to `OnlyCallableByArbitratorOrAfterChallengeTimeOutPeriod`

2022-06-21 13:21 UTC, ben-kaufman commented
Fixed

2022-06-24 10:21 UTC, jellegerbrandy submitted a review, later dismissed

2022-06-24 10:21 UTC, jellegerbrandy commented
Fix the conflicts and it is good to go :)

2022-06-24 13:35 UTC, jellegerbrandy approved these changes

2022-06-24 13:36 UTC, merged