update roles doc
hats-finance/hats-contracts pull request #282
Opened 2022-08-17 09:34 UTC by jellegerbrandy

2022-08-17 21:21 UTC, ben-kaufman commented on docs/roles.md
> -- can `transferOwnership` and `renounceOwnership`
Well that is possible no?

2022-08-18 17:21 UTC, lirona requested changes

2022-08-18 17:21 UTC, lirona commented on docs/roles.md
> +
```suggestion
- can call `setWithdrawalFee` on any vault - set the fee for withdrawals from the vault

```

2022-08-18 17:21 UTC, lirona commented on docs/roles.md
> +- can call `setWithdrawSafetyPeriod` set the amount of time during which claims can be submitted; during this time the vault users can not withdraw their funds. Must be less than 6 hours
```suggestion
- can call `setWithdrawSafetyPeriod` to set the withdraw period and safety period, which are always interchanging. The safety period is time can submit claims for bounty payouts, and during which withdrawals are disabled and the bounty split cannot be changed.
```

2022-08-18 17:21 UTC, lirona commented on docs/roles.md
> +- can call `setChallengePeriod`
```suggestion
- can call `setChallengePeriod` to set the time during which a claim can be challenged by the arbitrator
```

2022-08-18 17:21 UTC, lirona commented on docs/roles.md
> +  - `setAllocPoint`
```suggestion
  - `setAllocPoint`
  - `setCommittee`
```

2022-08-18 17:27 UTC, lirona commented on docs/roles.md
> +- can call `setClaimFee` set fee for submitting a vulnerability
```suggestion
- can call `setClaimFee` to set the fee for logging a claim for a bounty in any vault.
```

2022-08-19 09:17 UTC, jellegerbrandy commented on docs/roles.md
> +- can call `swapBurnSend` and swap, burn, and send the vauit's token that are earmarked for payout (after approveClaim)
why?

2022-08-19 11:54 UTC, lirona commented on docs/roles.md
> +- can call `swapBurnSend` and swap, burn, and send the vauit's token that are earmarked for payout (after approveClaim)
because swapBurnSend is run by the owner of the vault and not the registry

2022-08-19 12:58 UTC, merged

2022-08-19 14:02 UTC, lirona commented on docs/roles.md
> +- can call `setWithdrawSafetyPeriod` set the amount of time during which claims can be submitted; during this time the vault users can not withdraw their funds. Must be less than 6 hours
more accurate because it sets both